apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deviceshifu-driver
  namespace: devices
spec:
  serviceName: deviceshifu-driver
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-driver
  template:
    metadata:
      labels:
        app: deviceshifu-driver
    spec:
      nodeSelector:
        cpu: arm
      containers:
      - name: deviceshifu-driver
        image: deviceshifu-driver:latest
        imagePullPolicy: Never  # 强制使用本地镜像
        ports:
        - containerPort: 11311  # ROS master port
        env:
        - name: ROS_MASTER_URI
          value: "http://$(POD_IP):11311"
        - name: ROS_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: config-volume
          mountPath: /catkin_ws/src/deviceshifu_driver/config
      volumes:
      - name: config-volume
        configMap:
          name: deviceshifu-config
---
apiVersion: v1
kind: Service
metadata:
  name: deviceshifu-driver
  namespace: devices
spec:
  selector:
    app: deviceshifu-driver
  ports:
  - port: 11311
    targetPort: 11311
  type: ClusterIP 