apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deviceshifu-driver
  namespace: devices
spec:
  serviceName: deviceshifu-driver
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-driver
  template:
    metadata:
      labels:
        app: deviceshifu-driver
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 600
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 300
      containers:
        - name: deviceshifu-driver
          image: deviceshifu-driver:v1
          imagePullPolicy: Never
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          ports:
            - containerPort: 11311
              hostPort: 11311
            - containerPort: 11312
              hostPort: 11312
            - containerPort: 5000
              hostPort: 5000
          env:
            - name: ROS_MASTER_URI
              value: "http://192.168.31.101:11311"
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: ROS_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PYTHONPATH
              value: "/opt/ros/noetic/lib/python3/dist-packages:/catkin_ws/devel/lib/python3/dist-packages"
            - name: LD_LIBRARY_PATH
              value: "/opt/ros/noetic/lib:/catkin_ws/devel/lib"
            - name: ROS_ROOT
              value: "/opt/ros/noetic/share/ros"
            - name: ROS_PACKAGE_PATH
              value: "/opt/ros/noetic/share:/catkin_ws/src"
            - name: ROS_DISTRO
              value: "noetic"
          volumeMounts:
            - name: config-volume
              mountPath: /catkin_ws/src/deviceshifu_driver/config
            - name: tty-acm0
              mountPath: /dev/ttyACM0
            - name: tty-acm1
              mountPath: /dev/ttyACM1
      volumes:
        - name: config-volume
          configMap:
            name: deviceshifu-config
        - name: tty-acm0
          hostPath:
            path: /dev/ttyACM0
            type: CharDevice
        - name: tty-acm1
          hostPath:
            path: /dev/ttyACM1
            type: CharDevice
---
apiVersion: v1
kind: Service
metadata:
  name: deviceshifu-driver
  namespace: devices
spec:
  selector:
    app: deviceshifu-driver
  ports:
    - port: 11311
      targetPort: 11311
      name: ros-master
    - port: 11312
      targetPort: 11312
      name: ros-slave
  type: NodePort
