apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-bridge
  namespace: devices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-bridge
  template:
    metadata:
      labels:
        app: mqtt-bridge
    spec:
      containers:
      - name: mqtt-bridge
        image: ghcr.io/ika-rwth-aachen/mqtt_client:ros
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /config
        env:
        - name: ROS_MASTER_URI
          value: "http://$(HOST_IP):11311"
        - name: ROS_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumes:
      - name: config-volume
        configMap:
          name: mqtt-bridge-config 